title: NMDC Metadata schema
email: deepak.unni3@gmail.com
description: A schema for managing metadata in [National Microbiome Data Collaborative](https://microbiomedata.org/)

#remote_theme: deepakunni3/just-the-docs
theme: just-the-docs # build the docs using gem

aux_links:
  "GitHub":
    - "//github.com/microbiomedata/nmdc-metadata"

search_enabled: true
heading_anchors: true

exclude: ["examples/", "GOLD-level-analysis/", "GOLD-path-translation/", "identify/", "mapping-files/", "metadata-translation/", "MIxS-ontology-translation/", "scripts/", "update-docs.md"]
