name: Build and Deploy Static Mkdocs Documentation

# Controls when the action will run. Triggers the workflow on push
on:
  push:
    branches:
      - master
    paths:
      - 'mkdocs.yml'
      - 'schema/*.yaml'
      - 'docs/*'

  repository_dispatch:
    types: trigger-build-deploy-documentation

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
          
      # install dependencies
      - run: pip install --upgrade pip
      - run: pip install mkdocs
      - run: pip install biolinkml
        
      # generate markdown files
      - run: gen-markdown --dir docs schema/nmdc.yaml

      # deploy documentation (note: requires documentation is in docs dir)
      - run: mkdocs gh-deploy --remote-branch gh-pages --force --theme readthedocs
